const types = {
    SET_ERROR: 'SET_ERROR',
    SET_USER_LIST: 'SET_USER_LIST',
    RESET_STATE: 'RESET_STATE',
    SET_USER: 'SET_USER',
    SET_USER_TO_LOOK: 'SET_USER_TO_LOOK',
    RESET_USER_TO_LOOK: 'RESET_USER_TO_LOOK'
}

module.exports = types;